//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomaFm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastBalanceTrackBarValue {
            get {
                return ((int)(this["LastBalanceTrackBarValue"]));
            }
            set {
                this["LastBalanceTrackBarValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Groove Salad")]
        public string LastPlayerStreamName {
            get {
                return ((string)(this["LastPlayerStreamName"]));
            }
            set {
                this["LastPlayerStreamName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ice1.somafm.com/groovesalad-128-aac")]
        public string LastPlayerStreamUri {
            get {
                return ((string)(this["LastPlayerStreamUri"]));
            }
            set {
                this["LastPlayerStreamUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LastVolumeTrackBarValue {
            get {
                return ((int)(this["LastVolumeTrackBarValue"]));
            }
            set {
                this["LastVolumeTrackBarValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionsEnableAutoPlayChecked {
            get {
                return ((bool)(this["OptionsEnableAutoPlayChecked"]));
            }
            set {
                this["OptionsEnableAutoPlayChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionsEnableMultimediaKeysChecked {
            get {
                return ((bool)(this["OptionsEnableMultimediaKeysChecked"]));
            }
            set {
                this["OptionsEnableMultimediaKeysChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>{ group: \"Low-Lyric\", name: \"Groove Salad\", url: \"http://ice1.somafm.com/g" +
            "roovesalad-128-aac\" }</string>\r\n  <string>{ group: \"Low-Lyric\", name: \"Space Sta" +
            "tion\", url: \"http://ice1.somafm.com/spacestation-128-aac\" }</string>\r\n  <string>" +
            "{ group: \"Low-Lyric\", name: \"Drone Zone\", url: \"http://ice1.somafm.com/dronezone" +
            "-128-aac\" }</string>\r\n  <string>{ group: \"Low-Lyric\", name: \"Earwaves\", url: \"ht" +
            "tp://ice1.somafm.com/earwaves-128-aac\" }</string>\r\n  <string>{ group: \"Low-Lyric" +
            "\", name: \"Silent\", url: \"http://ice1.somafm.com/silent-128-aac\" }</string>\r\n  <s" +
            "tring>{ group: \"Low-Lyric\", name: \"SF 10-33\", url: \"http://ice2.somafm.com/sf103" +
            "3-64-aac\" }</string>\r\n  <string>{ group: \"Low-Lyric\", name: \"Mission Control\", u" +
            "rl: \"http://ice2.somafm.com/missioncontrol-64-aac\" }</string>\r\n  <string>{ group" +
            ": \"Low-Lyric\", name: \"Cliqhop IDM\", url: \"http://ice1.somafm.com/cliqhop-128-aac" +
            "\" }</string>\r\n  <string>{ group: \"Low-Lyric\", name: \"PopTron\", url: \"http://ice2" +
            ".somafm.com/poptron-64-aac\" }</string>\r\n  <string>{ group: \"Low-Lyric\", name: \"D" +
            "EF CON Radio\", url: \"http://ice1.somafm.com/defcon-128-aac\" }</string>\r\n  <strin" +
            "g>{ group: \"Low-Lyric\", name: \"Beat Blender\", url: \"http://ice1.somafm.com/beatb" +
            "lender-128-aac\" }</string>\r\n  <string>{ group: \"Low-Lyric\", name: \"Deep Space On" +
            "e\", url: \"http://ice1.somafm.com/deepspaceone-128-aac\" }</string>\r\n  <string>{ g" +
            "roup: \"Others\", name: \"Secret Agent\", url: \"http://ice1.somafm.com/secretagent-1" +
            "28-aac\" }</string>\r\n  <string>{ group: \"Others\", name: \"Lush\", url: \"http://ice1" +
            ".somafm.com/lush-128-aac\" }</string>\r\n  <string>{ group: \"Others\", name: \"Indie " +
            "Pop\", url: \"http://ice1.somafm.com/indiepop-128-aac\" }</string>\r\n  <string>{ gro" +
            "up: \"Others\", name: \"South\", url: \"http://ice2.somafm.com/sxfm-64-aac\" }</string" +
            ">\r\n  <string>{ group: \"Others\", name: \"Metal\", url: \"http://ice1.somafm.com/meta" +
            "l-128-aac\" }</string>\r\n  <string>{ group: \"Others\", name: \"Doomed\", url: \"http:/" +
            "/ice2.somafm.com/doomed-64-aac\" }</string>\r\n  <string>{ group: \"Others\", name: \"" +
            "Covers\", url: \"http://ice2.somafm.com/covers-64-aac\" }</string>\r\n  <string>{ gro" +
            "up: \"Others\", name: \"Dub Step Beyond\", url: \"http://ice2.somafm.com/dubstep-64-a" +
            "ac\" }</string>\r\n  <string>{ group: \"Others\", name: \"Black Rock FM\", url: \"http:/" +
            "/ice1.somafm.com/brfm-128-aac\" }</string>\r\n  <string>{ group: \"Others\", name: \"T" +
            "histleRadio\", url: \"http://ice1.somafm.com/thistle-128-aac\" }</string>\r\n  <strin" +
            "g>{ group: \"Others\", name: \"Digitalis\", url: \"http://ice1.somafm.com/digitalis-1" +
            "28-aac\" }</string>\r\n  <string>{ group: \"Others\", name: \"Seven Inch Soul\", url: \"" +
            "http://ice1.somafm.com/7soul-128-aac\" }</string>\r\n  <string>{ group: \"Others\", n" +
            "ame: \"Illinois Street Lounge\", url: \"http://ice1.somafm.com/illstreet-128-aac\" }" +
            "</string>\r\n  <string>{ group: \"Others\", name: \"Boot Liquor\", url: \"http://ice1.s" +
            "omafm.com/bootliquor-128-aac\" }</string>\r\n  <string>{ group: \"Others\", name: \"BA" +
            "GeL Radio\", url: \"http://ice2.somafm.com/bagel-64-aac\" }</string>\r\n  <string>{ g" +
            "roup: \"Others\", name: \"Fluid\", url: \"http://ice1.somafm.com/fluid-128-aac\" }</st" +
            "ring>\r\n  <string>{ group: \"Others\", name: \"Suburbs of Goa\", url: \"http://ice1.so" +
            "mafm.com/suburbsofgoa-128-aac\" }</string>\r\n  <string>{ group: \"Others\", name: \"S" +
            "onic Universe\", url: \"http://ice2.somafm.com/sonicuniverse-64-aac\" }</string>\r\n " +
            " <string>{ group: \"Others\", name: \"The Trip\", url: \"http://ice2.somafm.com/thetr" +
            "ip-64-aac\" }</string>\r\n  <string>{ group: \"Others\", name: \"Folk Forward\", url: \"" +
            "http://ice1.somafm.com/folkfwd-128-aac\" }</string>\r\n  <string>{ group: \"Others\"," +
            " name: \"Left Coast 70s\", url: \"http://ice1.somafm.com/seventies-128-aac\" }</stri" +
            "ng>\r\n  <string>{ group: \"Others\", name: \"Underground 80s\", url: \"http://ice1.som" +
            "afm.com/u80s-128-aac\" }</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Streams {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Streams"]));
            }
            set {
                this["Streams"] = value;
            }
        }
    }
}
